spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3308/seminar2?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
      
auth.jwt:
  jwtSecret: SEMINAR_SECRET_KEY
  
  # TODO 누락된 정보를 추가해 주세요.