

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
auth.jwt:
  jwtSecret: SEMINAR_SECRET_KEYfkrhsksmsakfgoTekdkfrpTsi
  issuer: TEST
  jwtExpiration: 86400

---

spring:
  profiles:
    active: dev
    
---

spring:
  profiles:
    active: prod


