spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create-drop

auth.jwt:
  jwtSecret: w9z$B&E)H@McQfTjWnZr4u7x!A%D*F-J
  issuer: seminar.wafflestudio.com
  jwtExpiration: 6000

---

#spring:
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://localhost:3308/seminar2?serverTimezone=UTC
#    username: root
#    password: 1234
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#    hibernate:
#      ddl-auto: update
#
#auth.jwt:
#  jwtSecret: SEMINAR_SECRET_KEYfkrhsksmsakfgoTekdkfrpTsi
#  issuer: TEST
#  jwtExpiration: 86400